// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using SIS.Extensions.TestGenerator.Models;

namespace SIS.Extensions.TestGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class Template : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("namespace ");
            
            #line 9 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(File.Namespace));
            
            #line default
            #line hidden
            this.Write(".Tests\r\n{\r\n\tusing Microsoft.VisualStudio.TestTools.UnitTesting;\r\n\tusing FakeItEas" +
                    "y;\r\n\t");
            
            #line 13 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join("\r\n\t", File.Usings
			.Select(x => string.Format("using {0};", x))
			.Union(new [] { string.Format("using {0};", File.Namespace) })
			.OrderBy(x => x))));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            
            #line 19 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"

	foreach(var currentClass in File.Classes)
	{
		var constructor = currentClass.Constructors
							   .OrderBy(x => x.Parameters.Count())
							   .FirstOrDefault();

		var constructorCall = constructor == null 
								? string.Format("{0}()", currentClass.Name) 
								: string.Format("{0}({1})", currentClass.Name, string.Join(",", constructor.Parameters.Select(x => x.Name)));
		
	
            
            #line default
            #line hidden
            this.Write("\t[TestClass]\r\n\tpublic class ");
            
            #line 32 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("{0}Tests", currentClass.Name)));
            
            #line default
            #line hidden
            this.Write(" \r\n\t{   \r\n\t\tprotected ");
            
            #line 34 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("{0}", currentClass.Name)));
            
            #line default
            #line hidden
            this.Write(" GetTarget() \r\n\t\t{\r\n\t\t\treturn new ");
            
            #line 36 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(constructorCall));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n\r\n\t\t[TestInitialize]\r\n\t\tpublic void Initialize() \r\n\t\t{\r\n\t\t\tFake.Initializ" +
                    "eFixture(this);\r\n\t\t}\r\n");
            
            #line 44 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"

		if(constructor != null) 
		{
            foreach (var parameter in constructor.Parameters)
            {

            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t[Fake]\r\n\t\tpublic ");
            
            #line 51 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("{0} {1}", parameter.Type, parameter.Name)));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 52 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"

            } 
		}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 57 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"


		foreach (var parameter in currentClass.GetMethodVariables())
        {


            
            #line default
            #line hidden
            this.Write("\t\tprotected ");
            
            #line 62 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("{0} {1}", parameter.Type, parameter.Name)));
            
            #line default
            #line hidden
            this.Write(" { get; set; } \r\n");
            
            #line 63 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"

        }
	
		if(constructor != null)
		{
			foreach(var parameter in constructor.Parameters) 
			{
				var parameterName = parameter.Name;
				var methodName= string.Format("GetTarget_Without{0}_ThrowsException", parameterName);

            
            #line default
            #line hidden
            this.Write("\r\n\t\t[TestMethod]\r\n\t\t[ExpectedException(typeof(ArgumentNullException))]\r\n\t\tpublic " +
                    "void ");
            
            #line 76 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("() \r\n\t\t{\r\n\t\t\t");
            
            #line 78 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("new {0}({1});", currentClass.Name, string.Join(",", constructor.Parameters.Select(x => x == parameter ? "null" : x.Name)))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n");
            
            #line 80 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"

			}
		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 84 "C:\Users\Peter\Documents\Visual Studio 2015\Projects\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Sgbdnl.Extensions.TestGenerator\Templates\Template.tt"

	}

            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class TemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
